apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbdeploy
  labels:
    app: sb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sb
  template:
    metadata:
      labels:
        app: sb
    spec:
      containers:
      - name: sbcont
        image: dockersatish124/repo2:latest
        ports:
        - containerPort: 8082
       
        
