apiVersion: v1
kind: Service
metadata:
  name: sbsvc
spec:
  type: NodePort  # Change the type to NodePort
  selector:
    app: sb
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30000  # Define the nodePort value
